### ISSUE TITLE
need help with installation

### ISSUE THREAD

**Issue by raoel** [dndtoolsnet/dndtools#3]
I have no experience at all with Python / Django.
I had to install pip (maybe add this as a requirement to the instruction).

But I am stuck now...

I am getting errors when I am following the steps for installation.

This is as a normal user, I did "pip install -r requirements.txt" and got this:
https://jpst.it/IH5-

I tried with sudo but that also does not work.

Anything else I could try?

uname -a:
Linux raoel-laptop 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a"
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 17.3 Rosa
Release:    17.3
Codename:   rosa

**Comment by raoel** [comment]
I followed the instructions in this file:
https://github.com/dndtoolsnet/dndtools/blob/master/INSTALL

I did the mysql-stuff manually, and after executing the 'runserver' command I got this:

```

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/raoel/Projects/raoel/dndtools/env/local/lib/python2.7/site-packages/Django-1.10a1-py2.7.egg/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/raoel/Projects/raoel/dndtools/env/local/lib/python2.7/site-packages/Django-1.10a1-py2.7.egg/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/home/raoel/Projects/raoel/dndtools/env/local/lib/python2.7/site-packages/Django-1.10a1-py2.7.egg/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/raoel/Projects/raoel/dndtools/env/local/lib/python2.7/site-packages/Django-1.10a1-py2.7.egg/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/raoel/Projects/raoel/dndtools/env/local/lib/python2.7/site-packages/Django-1.10a1-py2.7.egg/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/raoel/Projects/raoel/dndtools/dndtools/dndproject/settings.py", line 3, in <module>
    from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS
ImportError: cannot import name TEMPLATE_CONTEXT_PROCESSORS
```

I think this has something to do with a wrong version of Django?

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
>>> django.VERSION
(1, 10, 0, u'alpha', 1)


```

**Comment by raoel** [comment]
This helped:
sudo apt-get install python-dev
sudo apt-get install libmariadbclient-dev (or libmysqlclient-dev for mysql)

After migrating I now have a running site!

```

ImproperlyConfigured at /
Error importing debug panel debug_toolbar.panels.versions: "No module named versions"
Request Method: GET
Request URL:    http://127.0.0.1:8000/
Django Version: 1.5.5
Exception Type: ImproperlyConfigured
Exception Value:    
Error importing debug panel debug_toolbar.panels.versions: "No module named versions"
Exception Location: /home/raoel/Projects/raoel/dndtools/env/local/lib/python2.7/site-packages/debug_toolbar/toolbar/loader.py in load_panels, line 72
Python Executable:  /home/raoel/Projects/raoel/dndtools/env/bin/python
Python Version: 2.7.6
Python Path:    
['/home/raoel/Projects/raoel/dndtools/dndtools',
 '/home/raoel/Projects/raoel/dndtools/env/local/lib/python2.7/site-packages/django_pagination-1.0.7-py2.7.egg',
 '/home/raoel/Projects/raoel/dndtools/env/local/lib/python2.7/site-packages/sqlparse-0.1.19-py2.7.egg',
 '/home/raoel/Projects/raoel/dndtools/env/local/lib/python2.7/site-packages/recaptcha_client-1.0.6-py2.7.egg',
 '/home/raoel/Projects/raoel/dndtools/env/lib/python2.7',
 '/home/raoel/Projects/raoel/dndtools/env/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/raoel/Projects/raoel/dndtools/env/lib/python2.7/lib-tk',
 '/home/raoel/Projects/raoel/dndtools/env/lib/python2.7/lib-old',
 '/home/raoel/Projects/raoel/dndtools/env/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/raoel/Projects/raoel/dndtools/env/local/lib/python2.7/site-packages']
Server time:    Sat, 21 May 2016 11:44:07 +0200
```

**Comment by raoel** [comment]
I did:
pip install django-debug-toolbar 

and run again, but it's still not there. The toolbar is in INSTALLED_APPS, and it's referenced correctly in local.py according to the manual here:
http://django-debug-toolbar.readthedocs.io/en/1.4/installation.html

I set DEBUG = False

Now I just get a server error

```
500 - Server error

Whooops
```

which is not very informative :-)

And I can't find any logging.... 

Okay, that's enough for today :-)

**Comment by urheil** [comment]
Hi, I've never used Python before, but if I try I need to know: did you make it work?
